casa = float(input('Qual o valor da casa? R$'))
salario =  float(input('Qual o salário do comprador? R$'))
anos = int(input('Quantos anos de financiamento?'))
prestacao = casa/(anos*12)
print('Para pagar uma casa de R${:.2f} em {} anos, a prestação será de R${:.2f}'. format(casa,anos,prestacao))
if salario * 0.30 >= prestacao: print('Emprestimo aprovado!')
else: print('Emprestimo negado!')