peso = float(input('Quanto você pesa? (kg)'))
altura = float(input('Qual a sua altura? (m)'))
IMC = peso / (altura ** 2)
print('O seu IMC é {:.2f}'.format(IMC))
if IMC < 18.5: print('Abaixo do peso')
elif IMC < 25: print('Peso ideal')
elif IMC < 30: print('Sobrepeso')
elif IMC < 40: print('Obesidade')